### ISSUE TITLE
Issue with add-on

### ISSUE THREAD

**Issue by TLyrilusc** [Unlucky-Life/ankimon#120]
Hey here is the debug info. Can I have some feedback?

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22631

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Acer\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 29, in <module>
    from PyQt6.QtGui import *
ModuleNotFoundError: No module named 'PyQt6'

**Comment by Unlucky-Life** [comment]
It says on the ankiweb that you need Anki PyQt6 version to use Ankimon: 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/63649ecf-d851-4b7c-8d96-bc34af7249df)

**Comment by Unlucky-Life** [comment]
basically you need to got to ankiweb and install pyqt6: https://apps.ankiweb.net/

**Comment by Unlucky-Life** [comment]
then you can install the addon :)

**Comment by Unlucky-Life** [comment]
@TLyrilusc let me know if the issue persists :)

**Comment by TLyrilusc** [comment]
Hi thanks for the quick answer. I still encounter this issue here. Can you help check?

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1132, in generate_random_pokemon
    base_experience = search_pokeapi_db_by_id(id, "base_experience")
  File "C:\Users\Acer\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1993, in search_pokeapi_db_by_id
    with open(str(pokeapi_db_path), "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Acer\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files\\data_files\\pokeapi_db.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\Acer\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2050, in <module>
    name, id, level, ability, type, stats, enemy_attacks, base_experience, growth_rate, hp, max_hp, ev, iv, gender, battle_status, battle_stats = generate_random_pokemon()
  File "C:\Users\Acer\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1164, in generate_random_pokemon
    return generate_random_pokemon()  # Return the result of the recursive call
  File "C:\Users\Acer\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1164, in generate_random_pokemon
    return generate_random_pokemon()  # Return the result of the recursive call
  File "C:\Users\Acer\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1166, in generate_random_pokemon
    showInfo("Error", "Can't open the JSON File.")
  File "aqt.utils", line 296, in showInfo
TypeError: arguments did not match any overloaded call:
  QMessageBox(parent: Optional[QWidget] = None): argument 1 has unexpected type 'str'
  QMessageBox(icon: QMessageBox.Icon, title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.NoButton, parent: Optional[QWidget] = None, flags: Qt.WindowType = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 1 has unexpected type 'str'

**Comment by Unlucky-Life** [comment]
https://github.com/Unlucky-Life/ankimon/issues/32
Did you download the resources yet ?
@TLyrilusc

**Comment by TLyrilusc** [comment]
Yeah when I restarted Anki, it asked to download, but I believe it glitched and stopped halfway. Let me try reinstalling again. I appreciate the response.

**Comment by TLyrilusc** [comment]
@Unlucky-Life It's working now. Thanks so much! 
![image](https://github.com/Unlucky-Life/ankimon/assets/170355405/33773255-060b-4331-94f8-d2844e9e06bb)
