### ISSUE TITLE
Unable to update addon on Windows

### ISSUE THREAD

**Issue by AEM7** [Unlucky-Life/ankimon#127]
I have the same addons on my Mac and I was able to update with no issues. 

Here is the debug info from the error message:

```
Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.addons", line 1242, in _download_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.addons", line 1219, in <lambda>
  File "aqt.addons", line 1235, in _download_all
  File "aqt.addons", line 1180, in download_and_install_addon
  File "aqt.addons", line 469, in install
  File "aqt.addons", line 493, in _install
  File "aqt.addons", line 740, in backupUserFiles
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\AEM\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files' -> 'C:\\Users\\AEM\\AppData\\Roaming\\Anki2\\addons21\\files_backup'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T11:01, 'None', mod]
Add Hyperlink ['318752047', 2023-06-18T06:39, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-14T08:17, 'None', mod]
Batch Editing ['291119185', 2023-10-25T19:38, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T10:06, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T20:19, 'None', mod]
Enhance main window ['877182321', 2023-10-22T15:28, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T06:47, 'None', '']
Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T02:15, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-04-11T05:35, 'None', mod]
New Cards Counter ['635082046', 2022-04-20T15:37, 'None', '']
ReColor ['688199788', 2024-03-02T19:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
Special Fields ['1102281552', 2024-03-19T18:34, 'None', '']
The KING of Button Add-ons ['374005964', 2024-01-27T04:19, 'None', '']
The KING of Study Timers ['907028815', 2022-04-20T13:14, 'None', mod]
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T13:28, 'None', mod]
uworld_qid_to_anki_search ['607963104', 2024-04-13T13:56, 'None', mod]

===IDs of active AnkiWeb add-ons===
1102281552 1210908941 1374772155 1556734708 1771074083 1908235722 291119185 318752047 374005964 46611790 594329229 607963104 635082046 688199788 864545277 877182321 907028815

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiDiscord - Discord integration for Anki ['1133851639', 2020-01-13T19:53, 'None', '']
AnkiHub ['1322529746', 2024-05-27T09:37, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-02-29T19:22, 'v1.0.2', mod]
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-05-20T23:19, 'None', '']
Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-22T22:10, 'None', '']
Mobile Pop-up Dictionary ['1143247763', 2024-01-29T16:11, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T05:24, 'None', '']
```

**Comment by Unlucky-Life** [comment]
the issue seems to be here: PermissionError: [WinError 5] Access is denied: 'C:\\Users\\AEM\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files' -> 'C:\\Users\\AEM\\AppData\\Roaming\\Anki2\\addons21\\files_backup'

**Comment by Unlucky-Life** [comment]
2 weeks ago there were some with the same issue: https://github.com/Unlucky-Life/ankimon/issues/112 =>

**Comment by AEM7** [comment]
> 2 weeks ago there were some with the same issue: #112 => This seemed to work: Manual Backup and Install:
> 
> Manually back up your pokemons and user files from C:\Users\AEM\AppData\Roaming\Anki2\addons21\1908235722\user_files by copying the folder to another location. Then after backing up the user_files folder to another location => Delete the user_files Folder in Ankimon. Then, try updating the add-on again and after updating, manually copy paste back the above named folder.

This solution worked for me, the running addon and Anki as admin did not, but I was able to update successfully. Thank you!

**Comment by Unlucky-Life** [comment]
No problemo ! Thank you :)
