### ISSUE TITLE
AttributeError: module 'aqt.qt' has no attribute 'AspectRatioMode'

### ISSUE THREAD

**Issue by galantra** [Unlucky-Life/ankimon#136]
This is on Anki 24.06 and it's the first time I've tried your add-on. I can't tell yet whether it works ~~on an earlier version or~~ with other addons disabled.

```
Anki 24.06 (c4cd8808)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\emanresu\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5917, in <module>
    test_window = TestWindow()
  File "C:\Users\emanresu\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5297, in __init__
    self.init_ui()
  File "C:\Users\emanresu\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5315, in init_ui
    scaled_pixmap = pixmap.scaled(400, 400, Qt.AspectRatioMode.KeepAspectRatio)
AttributeError: module 'aqt.qt' has no attribute 'AspectRatioMode'


```

Edit: Same error on 24.04.1

**Comment by Unlucky-Life** [comment]
@galantra hm ok i havent seent that issue yet
Let met check that out today!

**Comment by Unlucky-Life** [comment]
@galantra right now 23.12.1 is working
Maybe the Ankimon Addon isnt fit for the newest Anki Update yet.

**Comment by shigeyukey** [comment]
That is odd, I use Anki 24.06.1 and Win11 (Python 3.9.18 Qt 6.6.2 PyQt 6.6.1), but that problem doesn't seem to happen, it's working fine.
