### ISSUE TITLE
TypeError: '<' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#14]
This error occurred when I tried to catch Genesect 😭
(Don't worry, I caught it somehow.)

```
Anki 24.04 (d516a9d9)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5255, in <lambda>
    qconnect(catch_button.clicked, lambda: catch_pokemon(nickname_input.text()))
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1672, in catch_pokemon
    new_pokemon()  # Show a new random Pokémon
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1724, in new_pokemon
    name, id, level, ability, type, stats, enemy_attacks, base_experience, growth_rate, hp, max_hp, ev, iv, gender, battle_status, battle_stats = generate_random_pokemon()
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1024, in generate_random_pokemon
    id_check = check_id_ok(id)
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 211, in check_id_ok
    if id_num < 898:
TypeError: '<' not supported between instances of 'list' and 'int'
```

**Comment by Foxy-null** [comment]
BTW, here's a screenshot of my Genesect! :)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/6b7183d6-1568-4542-a0ae-9cdd8fea1858)

**Comment by Unlucky-Life** [comment]
Yes there are a few issues with the min-level generate function due to the different pokemon names in poke api and pokemonshowdown

**Comment by Unlucky-Life** [comment]
i need to basically go through all the pokemon names between the name collections / databases i use and then basically re-match the name string when accessing these functions.

But I plan on fixing this for the next Update (will follow on Friday or Sunday)

**Comment by Unlucky-Life** [comment]
Quick Question: on the hoopla warning window - could you tell me / translate what the issue is there ?

**Comment by Foxy-null** [comment]
Sure!
It says that "Anki has encountered an issue. The following addon might be the cause of the problem:"

**Comment by Unlucky-Life** [comment]
Were you able to copy the debug information ?Am 12.03.2024 um 11:49 schrieb Foxy_null ***@***.***>:﻿
Sure!
It says that "Anki has encountered an issue. The following addon might be the cause of the problem:"

**Comment by Foxy-null** [comment]
Sure, here it is!
```
Anki 24.04 (d516a9d9)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5393, in <lambda>
    qconnect(catch_button.clicked, lambda: catch_pokemon(nickname_input.text()))
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1798, in catch_pokemon
    new_pokemon()  # Show a new random Pokémon
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1850, in new_pokemon
    name, id, level, ability, type, stats, enemy_attacks, base_experience, growth_rate, hp, max_hp, ev, iv, gender, battle_status, battle_stats = generate_random_pokemon()
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1150, in generate_random_pokemon
    id_check = check_id_ok(id)
  File "C:\Users\Foxy_null\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 337, in check_id_ok
    if id_num < 898:
TypeError: '<' not supported between instances of 'list' and 'int'
```

**Comment by Unlucky-Life** [comment]
amazing ! Okey now we know where the problematic function is, thank you !

**Comment by Unlucky-Life** [comment]
Found the issue and should be solved for the next update!
