### ISSUE TITLE
Unable to start.

### ISSUE THREAD

**Issue by xiongdy54** [Unlucky-Life/ankimon#153]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Ankimon:
Traceback (most recent call last):
  File "urllib3.connectionpool", line 536, in _make_request
  File "urllib3.connection", line 464, in getresponse
  File "C:\Users\xiong\AppData\Roaming\Anki2\addons21\111623432\external\sentry_sdk\integrations\stdlib.py", line 128, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "http.client", line 1377, in getresponse
  File "http.client", line 320, in begin
  File "http.client", line 281, in _read_status
  File "socket", line 704, in readinto
  File "ssl", line 1275, in recv_into
  File "ssl", line 1133, in read
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests.adapters", line 589, in send
  File "urllib3.connectionpool", line 843, in urlopen
  File "urllib3.util.retry", line 474, in increment
  File "urllib3.util.util", line 39, in reraise
  File "urllib3.connectionpool", line 789, in urlopen
  File "urllib3.connectionpool", line 538, in _make_request
  File "urllib3.connectionpool", line 369, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\xiong\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 324, in <module>
    online_connectivity = test_online_connectivity()
  File "C:\Users\xiong\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 315, in test_online_connectivity
    response = requests.get(url, timeout=timeout)
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 635, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=5)

**Comment by Unlucky-Life** [comment]
@xiongdy54 It looks like your internet connection is the issue.
Maybe try to got the the Ankimon settings and set SSL to false

**Comment by Unlucky-Life** [comment]
or you could start Anki with no Internet Connection => and then once Anki has started up you can activate your Internet Connection again.

ReadTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=5) => This issue tells me that your internet connection has set GitHub as non trustable resource and therefore the timeout happened

**Comment by Unlucky-Life** [comment]
Here might be a fix for your issue:
https://github.com/Unlucky-Life/ankimon/releases/download/1.288/ankimon-1.288-anki21-ankiweb.ankiaddon


Please install this file ^
and then replace the __init__ file with this one in the zip folder: 
[__init__.zip](https://github.com/user-attachments/files/16057355/__init__.zip)

I hope this should solve the issue !

**Comment by xiongdy54** [comment]
> Here might be a fix for your issue: https://github.com/Unlucky-Life/ankimon/releases/download/1.288/ankimon-1.288-anki21-ankiweb.ankiaddon
> 
> Please install this file ^ and then replace the **init** file with this one in the zip folder: [**init**.zip](https://github.com/user-attachments/files/16057355/__init__.zip)
> 
> I hope this should solve the issue !

Thank you so much for your response! After completing the first step - installing the plugin from the link you provided and then restarting Anki, it's working perfectly now! I've successfully caught a Makuhita!
