### ISSUE TITLE
Ankimon Window crashes after selecting new main Pokémon

### ISSUE THREAD

**Issue by xip0enix** [Unlucky-Life/ankimon#156]
So I changed my main Pokémon and tried to open the battle (Ankimon) window. Unfortunately, the window crashes because there is a division by original_width2, which has the value 0.

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2807, in <lambda>
    choose_pokemon_button.clicked.connect(lambda state, name=pokemon_name, nickname=pokemon_nickname, level=pokemon_level, id=pokemon_id, ability=pokemon_ability, type=pokemon_type, detail_stats=pokemon_stats, attacks=pokemon_attacks, hp=pokemon_hp, base_experience=pokemon_base_experience, growth_rate=pokemon_growth_rate, ev=pokemon_ev, iv=pokemon_iv, gender=pokemon_gender: MainPokemon(name, nickname, level, id, ability, type, detail_stats, attacks, hp, base_experience, growth_rate, ev, iv, gender))
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 3641, in MainPokemon
    new_pokemon() #new pokemon if you change your pokemon
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1857, in new_pokemon
    test_window.display_first_encounter()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5833, in display_first_encounter
    battle_widget = self.pokemon_display_first_encounter()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5500, in pokemon_display_first_encounter
    image_label, msg_font = window_show()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5414, in window_show
    new_height2 = (original_height2 * max_width) // original_width2
ZeroDivisionError: integer division or modulo by zero

**Comment by Unlucky-Life** [comment]
https://github.com/Unlucky-Life/ankimon/blob/main/missing_back_sprites/missing_back_sprites.zip
Just download this - left click to unzip - and then just place the sprites into the back_sprites folder :)

**Comment by Unlucky-Life** [comment]
Copy into This path specifically /user_files/sprites/back_default/

**Comment by xip0enix** [comment]
Thanks ❤️
