### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by dinghaol** [Unlucky-Life/ankimon#182]
I open anki,but it don't work.

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19041

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "F:\AnkiDataFolder\addons21\1908235722\__init__.py", line 6687, in <module>
    starter_window.display_starter_pokemon()
  File "F:\AnkiDataFolder\addons21\1908235722\__init__.py", line 6099, in display_starter_pokemon
    starter_label = self.pokemon_display_starter(water_start, fire_start, grass_start)
  File "F:\AnkiDataFolder\addons21\1908235722\__init__.py", line 6213, in pokemon_display_starter
    water_pixmap = resize_pixmap_img(water_pixmap)
  File "F:\AnkiDataFolder\addons21\1908235722\__init__.py", line 6209, in resize_pixmap_img
    new_height = (original_height * max_width) // original_width
ZeroDivisionError: integer division or modulo by zero

**Comment by Unlucky-Life** [comment]
Hi @dinghaol  ! Thats an easy fix: if you get this  bug:  => It means you are missing some back sprites, which you can manually install by going to
'https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites'
Download the missing sprites from this folder and place them in 'back_default' under 'user_files'/ 'sprites'  in the Ankimon Addon Folder
