### ISSUE TITLE
Plugin causes segfault on linux

### ISSUE THREAD

**Issue by ForgotMyPasswd** [Unlucky-Life/ankimon#186]
After installing this plugin, anki does not open until the plugin is disabled. This also happens when I disable my other plugins too.

Logs (from running anki in a terminal, not sure if there are other logs that can be provided):
```
Python module pip_system_certs is not installed. System certificate store and custom SSL certificates may not work. See: https://github.com/ankitects/anki/issues/3016
Preparing to run...
Qt warning: QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix 
2024-09-04 15:46:02,517:INFO:aqt.mediasrv: Serving on http://127.0.0.1:36571
Qt warning: Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries' 
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/lib/qt6/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/lib/qt6/qtwebengine_dictionaries'
todo: windows paths in import screen
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/aqt/addons.py", line 247, in loadAddons
    __import__(addon.dir_name)
  File "/home/farrah/.local/share/Anki2/addons21/1908235722/__init__.py", line 6687, in <module>
    starter_window.display_starter_pokemon()
  File "/home/farrah/.local/share/Anki2/addons21/1908235722/__init__.py", line 6099, in display_starter_pokemon
    starter_label = self.pokemon_display_starter(water_start, fire_start, grass_start)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/farrah/.local/share/Anki2/addons21/1908235722/__init__.py", line 6231, in pokemon_display_starter
    custom_font = load_custom_font(28)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/farrah/.local/share/Anki2/addons21/1908235722/__init__.py", line 4035, in load_custom_font
    custom_font.setPointSize(font_size)  # Adjust the font size as needed
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: setPointSize(self, a0: int): argument 1 has unexpected type 'float'

Qt warning: QPaintDevice: Cannot destroy paint device that is being painted 
Segmentation fault (core dumped)
```

System Information:
OS: Arch Linux using 6.10.7.zen1-1 kernel
Compositor: Hyprland
Display Protocol: Wayland
Anki version: 24.06.3 Qt6, installed via `anki-bin` package from AUR

**Comment by Unlucky-Life** [comment]
@ForgotMyPasswd I think I have seen that error before - i believe installing this release: https://github.com/Unlucky-Life/ankimon/releases/tag/1.288 => will solve your linux issue

**Comment by ForgotMyPasswd** [comment]
Fixed by using the tagged release from this repository, instead of the outdated version on AnkiWeb.
