### ISSUE TITLE
Plugin not loading (Linux, NixOS)

### ISSUE THREAD

**Issue by Vartroc** [Unlucky-Life/ankimon#198]
error:
```
Anki 24.06.3 (d678e393) (src) (ao)
Python 3.12.5 Qt 6.7.2 PyQt 6.7.0.dev2404081550
Platform: Linux-6.6.50-x86_64-with-glibc2.39

When loading Ankimon:
Traceback (most recent call last):
  File "/nix/store/l647fs4q051yvdxj4rx1741d8qv4qak0-anki-24.06.3/lib/python3.12/site-packages/aqt/addons.py", line 247, in loadAddons
    __import__(addon.dir_name)
  File "/home/andi/.local/share/Anki2/addons21/1908235722/__init__.py", line 36, in <module>
    from PyQt6.QtMultimediaWidgets import QVideoWidget
ModuleNotFoundError: No module named 'PyQt6.QtMultimediaWidgets'
```
fastfetch:
```
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖             andi@Gartroc
          ▜███▙       ▜███▙  ▟███▛             ------------
           ▜███▙       ▜███▙▟███▛              OS: NixOS 24.11.20240911.4f807e8 (Vicuna) x86_64
            ▜███▙       ▜██████▛               Host: B650E PG Riptide WiFi
     ▟█████████████████▙ ▜████▛     ▟▙         Kernel: Linux 6.6.50
    ▟███████████████████▙ ▜███▙    ▟██▙        Uptime: 2 hours, 5 mins
           ▄▄▄▄▖           ▜███▙  ▟███▛        Packages: 5469 (nix-system)
          ▟███▛             ▜██▛ ▟███▛         Shell: bash 5.2.32
         ▟███▛               ▜▛ ▟███▛          Display (LG ULTRAGEAR): 2560x1440 @ 165 Hz (as 2276x1280) in 27″ [External]
▟███████████▛                  ▟██████████▙    WM: river (Wayland)
▜██████████▛                  ▟███████████▛    Theme: Catppuccin-Mocha-Lavender [Qt], catppuccin-mocha-lavender-standard [GTK2/3/4]
      ▟███▛ ▟▙               ▟███▛             Icons: Papirus-Dark [Qt], Papirus-Dark [GTK2/3/4]
     ▟███▛ ▟██▙             ▟███▛              Font: DejaVu Sans (12pt) [Qt]
    ▟███▛  ▜███▙           ▝▀▀▀▀               Cursor: Bibata-Modern-Classic (20px)
    ▜██▛    ▜███▙ ▜██████████████████▛         Terminal: kitty 0.36.1
     ▜▛     ▟████▙ ▜████████████████▛          Terminal Font: FiraCodeNFM-Reg (11pt)
           ▟██████▙       ▜███▙                CPU: AMD Ryzen 5 7600X (12) @ 5.45 GHz
          ▟███▛▜███▙       ▜███▙               GPU 1: AMD Radeon RX 6950 XT [Discrete]
         ▟███▛  ▜███▙       ▜███▙              GPU 2: AMD Raphael [Integrated]
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘              Memory: 12.73 GiB / 30.48 GiB (42%)
                                               Swap: Disabled
                                               Disk (/): 93.92 GiB / 1.38 TiB (7%) - zfs
                                               Local IP (enp13s0): 192.168.188.78/24
                                               Locale: de_DE.UTF-8
```
If you need any other info, feel free to ask, but keep in mind that I am quite busy at the moment, so you may have to wait a day

**Comment by Unlucky-Life** [comment]
@Vartroc Im quite sorry, because I have not experience in Linux and this is the first time seeing this issue.

**Comment by Unlucky-Life** [comment]
@Vartroc Do you have any coding experience perhaps ?
If so, it seems like your PyQt6 is missing a module that is found on the Anki Mac and Windows Version

You could go into the __init__.py code and search for the places where the QVideoWidget is mentioned

**Comment by Vartroc** [comment]
I use NixOS which ist quite exotic and thus may Not have that specific version preinstalled. I May be able to install that library without having to do any coding (I only have basic python knowledge)

**Comment by Unlucky-Life** [comment]
@Vartroc Let me know if it works !

**Comment by shigeyukey** [comment]
It seems to import fine on my Linux Ubuntu.

**Comment by Unlucky-Life** [comment]
maybe @OuraN2O knows something ?

**Comment by OuraN2O** [comment]
Hi @Vartroc ! Do you still experience this issue with the updated version of anki ? Also I see that your anki is in python 3.12, compared to mine (versions 24.11 and 25.01 on Gentoo Linux) that are with python 3.9. 
I have these versions of pyqt6
![Image](https://github.com/user-attachments/assets/d09b4625-27ff-41ee-b89d-649b6ecab9ff)
My anki is installed directly from the anki github.
Apart from telling you all that I don't have any experience with NixOs and because it's a very different linux distro I wouldn't be of much help. 
I also found on the wiki that the `anki` package is deprecated in NixOs and you should use `anki-bin` (https://nixos.wiki/wiki/Anki), I think that's what eljamm pointed out.
Either way I hope it's enough to fix your problem

**Comment by eljamm** [comment]
> I also found on the wiki that the anki package is deprecated in NixOs and you should use anki-bin (https://nixos.wiki/wiki/Anki), I think that's what eljamm pointed out.

Just to clarify, not only is that not the official NixOS wiki, but it's also wrong and out of date as the `anki` package is not deprecated. In the [NixOS Search](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=anki) website, you can see that the package still exists and that both `anki` and `anki-bin` are at the same version. As such, you should use the [official Wiki](https://wiki.nixos.org/wiki/Anki) going forward for more accurate information.

That said, users are probably still better off using the `anki-bin` package for a seamless experience with this addon on NixOS.

**Comment by Vartroc** [comment]
Hello guys,
first off, let me apologize for not being active here, I had a lot going on irl. 
So after reading everything stated here, I tried using `anki-bin` and look at that, it worked flawlessly. Thanks too you all!
