### ISSUE TITLE
Add-on stopped working after I restarted Anki

### ISSUE THREAD

**Issue by andrewtuanta** [Unlucky-Life/ankimon#199]
Hello,

I restarted my Anki for the first time in like a week and the add-on stopped working.

Here's what the Debug info said:

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.0-arm64-arm-64bit

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "urllib3.connectionpool", line 536, in _make_request
  File "urllib3.connection", line 464, in getresponse
  File "http.client", line 1377, in getresponse
  File "http.client", line 320, in begin
  File "http.client", line 281, in _read_status
  File "socket", line 704, in readinto
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests.adapters", line 589, in send
  File "urllib3.connectionpool", line 843, in urlopen
  File "urllib3.util.retry", line 474, in increment
  File "urllib3.util.util", line 39, in reraise
  File "urllib3.connectionpool", line 789, in urlopen
  File "urllib3.connectionpool", line 538, in _make_request
  File "urllib3.connectionpool", line 369, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/andre/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 317, in <module>
    online_connectivity = test_online_connectivity()
  File "/Users/andre/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 308, in test_online_connectivity
    response = requests.get(url, timeout=timeout)
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 635, in send
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=5)

**Comment by Unlucky-Life** [comment]
@andrewtuanta Hm thats weird (best to just run Anki in Offline Mode by turning wifi off)
You seem to be using your PC from somewhere, where the connection to Google isnt allowed

=> Could you try this out ?

**Comment by andrewtuanta** [comment]
Hello,

It worked! I think it was just blocked on the hospital wifi. Thanks.

**Comment by Unlucky-Life** [comment]
@andrewtuanta Damn weird that google.com is being blocked on your hospital wifi ! 🗡️ :D
