### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by APLPTY** [Unlucky-Life/ankimon#200]
When I get to about 99% of the resources downloaded, a popup pops up telling that it's failing

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\29979\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6687, in <module>
    starter_window.display_starter_pokemon()
  File "C:\Users\29979\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6099, in display_starter_pokemon
    starter_label = self.pokemon_display_starter(water_start, fire_start, grass_start)
  File "C:\Users\29979\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6213, in pokemon_display_starter
    water_pixmap = resize_pixmap_img(water_pixmap)
  File "C:\Users\29979\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6209, in resize_pixmap_img
    new_height = (original_height * max_width) // original_width
ZeroDivisionError: integer division or modulo by zero

**Comment by Unlucky-Life** [comment]
Its a quick fix: This means you are missing some back sprites which you can manually install by going to
https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
Download the missing sprites from this folder and place them in 'back_default' under 'sprites / user_files' in the Ankimon Addon Folder
