### ISSUE TITLE
Download Resource not working on M1 Macbook Pro

### ISSUE THREAD

**Issue by Minoqi** [Unlucky-Life/ankimon#204]
**Bug:** 
"Download Resource" downloads for a while before crashing Anki causing in a failure to download properly. It disappears from the top bar as well.

**Steps Taken:** 
1. Restart anki
2. Remove from add-ons and re-add it, starting the process over

**Platform:**
M1 Macbook Pro on Anki Version ⁨24.06.3 (d678e393)⁩ and Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

**Debug Info:**
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/minoqi/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 6687, in <module>
    starter_window.display_starter_pokemon()
  File "/Users/minoqi/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 6099, in display_starter_pokemon
    starter_label = self.pokemon_display_starter(water_start, fire_start, grass_start)
  File "/Users/minoqi/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 6213, in pokemon_display_starter
    water_pixmap = resize_pixmap_img(water_pixmap)
  File "/Users/minoqi/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 6209, in resize_pixmap_img
    new_height = (original_height * max_width) // original_width
ZeroDivisionError: integer division or modulo by zero

**Comment by Unlucky-Life** [comment]
There is an easy fix to this: 
https://github.com/Unlucky-Life/ankimon/releases/download/1.288/ankimon-1.288-anki21-ankiweb.ankiaddon
^download the file above - double click to install - this includes all sprite files needed

**Comment by Unlucky-Life** [comment]
The download can be due to multiple reasons - like hibernation or the server (that i dont host) not being able to carry the load for downloading

**Comment by Unlucky-Life** [comment]
Let me know if it works ! :)

**Comment by Minoqi** [comment]
Yes thanks! It's a neat addon :)

**Comment by Minoqi** [comment]
It's probably the server since I know my laptop never went to sleep cuz I was watching youtube lol
