### ISSUE TITLE
Unable to open Ankimon window / change main pokemon

### ISSUE THREAD

**Issue by chi-tony** [Unlucky-Life/ankimon#234]
Hi, after catching or defeating a pokemon recently, I ran into a recurring bug that I can't remove. Anytime I interact with anything outside of the anki window, I get a divide by zero error - log below.

Log:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.26100

Traceback (most recent call last):
  File "C:\Users\tonyc\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2807, in <lambda>
    choose_pokemon_button.clicked.connect(lambda state, name=pokemon_name, nickname=pokemon_nickname, level=pokemon_level, id=pokemon_id, ability=pokemon_ability, type=pokemon_type, detail_stats=pokemon_stats, attacks=pokemon_attacks, hp=pokemon_hp, base_experience=pokemon_base_experience, growth_rate=pokemon_growth_rate, ev=pokemon_ev, iv=pokemon_iv, gender=pokemon_gender: MainPokemon(name, nickname, level, id, ability, type, detail_stats, attacks, hp, base_experience, growth_rate, ev, iv, gender))
  File "C:\Users\tonyc\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 3641, in MainPokemon
    new_pokemon() #new pokemon if you change your pokemon
  File "C:\Users\tonyc\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1857, in new_pokemon
    test_window.display_first_encounter()
  File "C:\Users\tonyc\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5833, in display_first_encounter
    battle_widget = self.pokemon_display_first_encounter()
  File "C:\Users\tonyc\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5500, in pokemon_display_first_encounter
    image_label, msg_font = window_show()
  File "C:\Users\tonyc\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5414, in window_show
    new_height2 = (original_height2 * max_width) // original_width2
ZeroDivisionError: integer division or modulo by zero

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Review Bottom Bar ['1136455830', 2024-08-22T07:04, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-16T11:07, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T06:18, 'None', '']
CrowdAnki JSON exportimport Edit history Collaborate on deck creation ['1788670778', 2023-10-30T14:57, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-11-25T21:42, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-10-03T22:54, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Life Drain ['715575551', 2024-12-03T01:44, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']

===IDs of active AnkiWeb add-ons===
111623432 1136455830 1374772155 1771074083 1788670778 1908235722 2494384865 46611790 715575551 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Unlucky-Life** [comment]
This is an easy fix ! @ZAMZAM997 @12zzzaaa @439qi @anbzerc

https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
=> You can download the zip file in here and unpack the zip file on your system with right click (best to have an application like 7zip for this).

(unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)

You can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window.

Click on the View Files button, and a folder will pop up.
from there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded

Restart Anki and you should be good to go !

**Comment by chi-tony** [comment]
awesome, it worked! thank you for the amazing addon @Unlucky-Life!!

**Comment by chi-tony** [comment]
awesome, it worked! thank you for the amazing addon @Unlucky-Life!!
