### ISSUE TITLE
Various rendering functions giving type errors

### ISSUE THREAD

**Issue by Interrobang01** [Unlucky-Life/ankimon#240]
I am using Linux Mint 21.3

After downloading the game files, when I went to open Anki (which should have displayed the starter pokemon screen), it didn't open. I ran it with terminal on and got the following log:

```
Preparing to run...
Gtk-Message: 15:01:44.264: Failed to load module "xapp-gtk3-module"
Qt warning: Qt: Session management error: Could not open network socket
2024-12-24 15:01:44,497:INFO:aqt.mediasrv: Serving on http://127.0.0.1:40375
Qt warning: Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/aqt/addons.py", line 250, in loadAddons
	__import__(addon.dir_name)
  File "/home/interrobang/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1908235722/__init__.py", line 6687, in <module>
	starter_window.display_starter_pokemon()
  File "/home/interrobang/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1908235722/__init__.py", line 6099, in display_starter_pokemon
	starter_label = self.pokemon_display_starter(water_start, fire_start, grass_start)
                	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/interrobang/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1908235722/__init__.py", line 6231, in pokemon_display_starter
	custom_font = load_custom_font(28)
              	^^^^^^^^^^^^^^^^^^^^
  File "/home/interrobang/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1908235722/__init__.py", line 4035, in load_custom_font
	custom_font.setPointSize(font_size)  # Adjust the font size as needed
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: setPointSize(self, a0: int): argument 1 has unexpected type 'float'

Qt warning: QPaintDevice: Cannot destroy paint device that is being painted
```

Now, I didn't wait 30 minutes for the game files to download for nothing, so I went and added `int()` to the argument in `SetPointSize()` on line 4035.

I launched Anki again and... it worked! Anki ran! I did not expect that. The UI in the study screen appears to work fine:
![image](https://github.com/user-attachments/assets/8188ac26-fe60-4bd5-90e0-5807fb3d12a7)

Unfortunately, opening the Ankimon window failed and gave another error:
```
Following Error occured when opening window: arguments did not match any overloaded call:
  drawRect(self, rect: QRectF): argument 1 has unexpected type 'int'
  drawRect(self, x: int, y: int, w: int, h: int): argument 3 has unexpected type 'float'
  drawRect(self, r: QRect): argument 1 has unexpected type 'int'
```
Now, I've come this far, so I went to line 5440 and added `int()` to `hp_bar_value` in `draw_hp_bar`. Unfortunately the window still didn't open, returning a different error:
```
Following Error occured when opening window: arguments did not match any overloaded call:
  drawPixmap(self, targetRect: QRectF, pixmap: QPixmap, sourceRect: QRectF): argument 1 has unexpected type 'float'
  drawPixmap(self, targetRect: QRect, pixmap: QPixmap, sourceRect: QRect): argument 1 has unexpected type 'float'
  drawPixmap(self, p: QPointF, pm: QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, p: QPoint, pm: QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, r: QRect, pm: QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, x: int, y: int, pm: QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, x: int, y: int, w: int, h: int, pm: QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, x: int, y: int, w: int, h: int, pm: QPixmap, sx: int, sy: int, sw: int, sh: int): argument 1 has unexpected type 'float'
  drawPixmap(self, x: int, y: int, pm: QPixmap, sx: int, sy: int, sw: int, sh: int): argument 1 has unexpected type 'float'
  drawPixmap(self, p: QPointF, pm: QPixmap, sr: QRectF): argument 1 has unexpected type 'float'
  drawPixmap(self, p: QPoint, pm: QPixmap, sr: QRect): argument 1 has unexpected type 'float'
```
Since there are 32 results for `drawPixMap`, I decided to give up and write this report.
Clicking on the Ankimon dropdown after either of these errors crashed Anki with no message in terminal.
At this point I decided to restart and try the other buttons in the Ankimon dropdown. The ones I tried seemed to work except for Itembag and Achievements, which gave a generic error message with the following debug outputs:

Itembag:
```
Anki 24.11 (87ccd24e) (src) (ao)
Python 3.11.10 Qt 6.7.3 PyQt 6.7.1
Platform: Linux-5.15.0-126-generic-x86_64-with-glibc2.38

Traceback (most recent call last):
  File "/home/interrobang/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1908235722/__init__.py", line 7061, in show_window
	self.move(x, y)
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Ankimon by Unlucky-life ['1908235722', 2024-05-16T08:07, 'None', '']

===IDs of active AnkiWeb add-ons===
1908235722

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

```
Achievements:
```
Anki 24.11 (87ccd24e) (src) (ao)
Python 3.11.10 Qt 6.7.3 PyQt 6.7.1
Platform: Linux-5.15.0-126-generic-x86_64-with-glibc2.38

Traceback (most recent call last):
  File "/home/interrobang/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1908235722/__init__.py", line 7258, in show_window
	self.move(x, y)
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Ankimon by Unlucky-life ['1908235722', 2024-05-16T08:07, 'None', '']

===IDs of active AnkiWeb add-ons===
1908235722

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

```

It was only at this point that I remembered to search the Github issues, where I then found #202. I downloaded the back sprites as instructed and placed them in user_files/sprites/back_default, whereupon it only asked whether to replace one file, so I guess I was missing them after all. It unfortunately did not fix any of the errors I was encountering at this point.

This seems related to #205 and also maybe #129.

**Comment by Unlucky-Life** [comment]
Tbh i dont know enough about linux and would propably need your help because this seems to be all typeerrors because they arent always predefined

**Comment by Interrobang01** [comment]
If i'm being honest i don't know enough about linux either.

I did find this https://docs.ankiweb.net/platform/linux/distro-packages.html
I originally installed anki with flathub, but with this in mind i downloaded it from the website instead, and now ankimon works. So I guess it's the package maintainers' faults?

One of the known issues at the repo here https://github.com/flathub/net.ankiweb.Anki is "Fractional scaling does not work, only scales by whole numbers". That would seem to be the problem! Running the app as is suggested doesn't seem to fix it, though.

**Comment by Unlucky-Life** [comment]
@OuranoH2O maybe he knows better ? (He is one of the linux experts on here) or @anbzerc ?

**Comment by OuraN2O** [comment]
Tbh I don't know much about the flatpak version of anki as I don't use it (h0tp does), but I recall seeing that the mint package is not well maintained and shouldn't be used. 
Either way if anki and the addon work when downloading the `linux-qt6.tar.zst ` file from the anki github, we could conclude that it's the package maintainer fault. @Unlucky-Life Maybe it would be useful to add this "disclaimer" when posting issues for linux as it would eliminate/reduce the variable of package manager/maintainer. 

> One of the known issues at the repo here https://github.com/flathub/net.ankiweb.Anki is "Fractional scaling does not work,
only scales by whole numbers". That would seem to be the problem! Running the app as is suggested doesn't seem to fix it, though.

Fractional scaling and by extension wayland is still a work in progress in most (if not all) desktop environment and in anki itself (last time I checked the progress for wayland integration). See the [open issue of dae for wayland](https://github.com/ankitects/anki/issues/1767). But I don't think fractional scaling should interfere with the addon, apart from being blurry, like with all other fractional scaling mishap. 

To conclude, if it works with the "official" anki downloaded from github, it's a problem of the package maintained by a third party (flatpak or the distro package maintainer). And if it works fine at 100% (or 200%) scaling, it's a wayland/DE problem

**Comment by Unlucky-Life** [comment]
@OuraN2O Where would be the best place to add this info ? 

`@Unlucky-Life Maybe it would be useful to add this "disclaimer" when posting issues for linux as it would eliminate/reduce the variable of package manager/maintainer.`

**Comment by OuraN2O** [comment]
> [@OuraN2O](https://github.com/OuraN2O) Where would be the best place to add this info ?

I think it would have its place in the readme, under the section important notes, or under a new section that could be called "Before reporting an issue". 
And/or we could look into an issue template for github so that it would guide people trying to report an issue when opening the issue directly. I think both is great, more is better

**Comment by Unlucky-Life** [comment]
@OuraN2O ok will do - and what exactly do we write there ?

I dont know too much about the linux systems. What would be the best way to phrase this issue / notice ?

**Comment by OuraN2O** [comment]
Something in the lines of 
"Before reporting an issue on Linux, make sure you check if it works with the package downloaded directly from the [Anki github](https://github.com/ankitects/anki/releases) as it could be a problem with the package maintained by a third party (distro maintainer or flatpak)"
For the issue template maybe a tick box with "[Linux] I made sure the issue occurs on the official github package"
If you want to reformulate don't hesitate, I don't think my syntax in english is at its best lol

**Comment by Unlucky-Life** [comment]
@OuraN2O I think this is good ! - i did add it to the read me now :) !
