### ISSUE TITLE
There are frequent pop-up error messages.

### ISSUE THREAD

**Issue by OnePear96** [Unlucky-Life/ankimon#241]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.26100

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 695, in _onBridgeCmd
  File "C:\Users\unepoire\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 7736, in linkHandler_wrap
    defeat_shortcut_function()
  File "C:\Users\unepoire\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 7700, in defeat_shortcut_function
    new_pokemon()
  File "C:\Users\unepoire\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1876, in new_pokemon
    test_window.display_first_encounter()
  File "C:\Users\unepoire\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6093, in display_first_encounter
    battle_widget = self.pokemon_display_first_encounter()
  File "C:\Users\unepoire\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5760, in pokemon_display_first_encounter
    image_label, msg_font = window_show()
  File "C:\Users\unepoire\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5674, in window_show
    new_height2 = (original_height2 * max_width) // original_width2
ZeroDivisionError: integer division or modulo by zero

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Ankimon ['1908235722', 2024-06-03T02:53, 'None', '']

===IDs of active AnkiWeb add-ons===
1908235722

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Unlucky-Life** [comment]
This is an easy fix ! @OnePear96 

https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
=> You can download the zip file in here and unpack the zip file on your system with right click (best to have an application like 7zip for this).

(unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)

You can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window.

Click on the View Files button, and a folder will pop up.
from there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded

Restart Anki and you should be good to go !

**Comment by OnePear96** [comment]
Thank you, fixed!
