### ISSUE TITLE
errors whenever i capture a new pokemon

### ISSUE THREAD

**Issue by laurenchiang** [Unlucky-Life/ankimon#243]
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.1.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/lauren/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 5810, in <lambda>
    qconnect(catch_button.clicked, lambda: catch_pokemon(nickname_input.text()))
  File "/Users/lauren/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1805, in catch_pokemon
    new_pokemon()  # Show a new random Pokémon
  File "/Users/lauren/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1862, in new_pokemon
    update_life_bar(reviewer, 0, 0)
NameError: name 'update_life_bar' is not defined

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Killstreaks - Reward Medals for Correct Answers Fixed by Shige ['1562475180', 2024-09-19T11:43, 'None', mod]
Anki Leaderboard - Compete with friends to boost motivation Fork by Shige ['175794613', 2024-12-01T22:07, 'None', mod]
Ankimon by Unlucky-life ['1908235722', 2024-05-16T08:07, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T03:18, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1562475180 175794613 1771074083 1908235722 2494384865

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Unlucky-Life** [comment]
@laurenchiang Did you restart Anki after choosing your starter by chance ?
