### ISSUE TITLE
 Download stuck/crash/problem after update

### ISSUE THREAD

**Issue by Unlucky-Life** [Unlucky-Life/ankimon#32]
This is a **mac** specific issue:
It's working now, as long as you babysit the download and not letting the laptop go to sleep/hibernating ... Pressing download and leaving the Download Window will cause the error

Do not download the resources in Fullscreen mode - this apparently creates the error aswell.

**Comment by Unlucky-Life** [comment]
https://pixeldrain.com/u/cwd49pLt

**Comment by 363738lp666** [comment]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\27020\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6687, in <module>
    starter_window.display_starter_pokemon()
  File "C:\Users\27020\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6099, in display_starter_pokemon
    starter_label = self.pokemon_display_starter(water_start, fire_start, grass_start)
  File "C:\Users\27020\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6213, in pokemon_display_starter
    water_pixmap = resize_pixmap_img(water_pixmap)
  File "C:\Users\27020\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6209, in resize_pixmap_img
    new_height = (original_height * max_width) // original_width
ZeroDivisionError: integer division or modulo by zero

这个怎么解决

**Comment by zozowohlg** [comment]
Hi! Wondering if anyone has been having the issue of anki just quitting when you click "Proceed" from the terms and conditions page for downloading resources. I've tried manually downloading the resources with the pixeldrain link, updating anki, removing and re-installing the add-on, restarting everything, no avail. Thanks!

**Comment by sir1careless** [comment]
Hi, you managed to download Ankimon, but the moment I restart my Anki so I can use it, the message appears: "Extension Initialization Error". It informs that it was not possible to perform the update properly. I use Anki version 25.02

I copied the error code so the developer can help me.

Furthermore, excellent work! 

Below is the error code:

Anki 25.02 (038d85b1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1132, in generate_random_pokemon
    base_experience = search_pokeapi_db_by_id(id, "base_experience")
  File "C:\Users\Lucas\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1993, in search_pokeapi_db_by_id
    with open(str(pokeapi_db_path), "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Lucas\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files\\data_files\\pokeapi_db.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 250, in loadAddons
  File "C:\Users\Lucas\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2050, in <module>
    name, id, level, ability, type, stats, enemy_attacks, base_experience, growth_rate, hp, max_hp, ev, iv, gender, battle_status, battle_stats = generate_random_pokemon()
  File "C:\Users\Lucas\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1166, in generate_random_pokemon
    showInfo("Error", "Can't open the JSON File.")
  File "aqt.utils", line 304, in showInfo
TypeError: arguments did not match any overloaded call:
  QMessageBox(parent: Optional[QWidget] = None): argument 1 has unexpected type 'str'
  QMessageBox(icon: QMessageBox.Icon, title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.NoButton, parent: Optional[QWidget] = None, flags: Qt.WindowType = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 1 has unexpected type 'str'
