### ISSUE TITLE
Ankimon isn't appearing; can't download additional resources.

### ISSUE THREAD

**Issue by Dubuyu** [Unlucky-Life/ankimon#38]
I am receiving the notification saying that I need to download the additional resources, but am not given the option to do so.
Receiving this notification:
![image](https://github.com/Unlucky-Life/ankimon/assets/90246693/af644af4-0292-4cba-81fb-99254edfe914)
And the following debug info:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "urllib3.connectionpool", line 467, in _make_request
  File "urllib3.connectionpool", line 1096, in _validate_conn
  File "urllib3.connection", line 642, in connect
  File "urllib3.connection", line 782, in _ssl_wrap_socket_and_match_hostname
  File "urllib3.util.ssl_", line 470, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 514, in _ssl_wrap_socket_impl
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1041, in _create
  File "ssl", line 1310, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3.connectionpool", line 790, in urlopen
  File "urllib3.connectionpool", line 491, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests.adapters", line 486, in send
  File "urllib3.connectionpool", line 844, in urlopen
  File "urllib3.util.retry", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Unlucky-Life/ankimon/main/update_txt.md (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\IWong25\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 265, in <module>
    github_content, github_html_content = read_github_file(github_url)
  File "C:\Users\IWong25\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 229, in read_github_file
    response = requests.get(url)
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Unlucky-Life/ankimon/main/update_txt.md (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

Any fixes? It may be useful to know that I am using a non-personal laptop with browsing restrictions.
Thanks for all the hard work that has clearly been put into this add-on.

**Comment by Unlucky-Life** [comment]
Hi Thanks for the nice words !
It seems like that you do have a issue due to the browsing restrictions.
That issue seems to be the corresponding with my github notification file and the help guide file on github.
Download this file: 
`https://we.tl/t-JtURvCggje`
and rename it as `__init__.py`.
Then replace this file with `__init__.py` in the ankimon addon_folder.
This is a workaround for the internet restrictions issues that i can see there. With this you should be able to start Ankimon.
You may have an issue tho, when downloading the resource files.
Reply to this issue again, if the downloading issue is a problem and i will try to help you out personally - so you can simple drag and drop files.

**Comment by Dubuyu** [comment]
Again, appreciate how passionate you are about this project, will make sure to at least send you coffee even if it doesn't work. Unfortunately I think I still can't download the additional resources. It seems to be stopping when trying to contact pokemon showdown.

**Comment by Unlucky-Life** [comment]
else if you like - i could send you a complete addon file if you send me your email. If the rework doesnt work.

**Comment by Dubuyu** [comment]
That would be so amazing, thanks. Email is Isaacwongsyd@gmail.com.

Where should I put said files?

**Comment by omfgroflmfaol** [comment]
I seem to have a similar issue with anki not being able to verify my ssh keys (I suppose that this might be because I'm currently stuck using eduroam or a mobile hotspot). I found workarounds for that by disabling ssh verification both for anki in general as well as in the request.get function of ankimon's __init__.py file. Ankimon now does load successfully, but anki crashes when I try to download the resources. I'm at my wits end as there is nothing for me to decipher in the macOS crash report. Can you send me the patched __init__.py or the complete plugin file so I can try if it fixes it? My mail is johannes.rojan@gmail.com

I'm so excited to try ankimon, spent all day trying to find out what's causing the issues :))

**Comment by Unlucky-Life** [comment]
Hey im sorry, i completely missed your last message !

**Comment by Unlucky-Life** [comment]
@Dubuyu @omfgroflmfaol 
Here is a link to the files u would normally need to download:
https://we.tl/t-aViO1emrOD
Steps to go through:
1. unzip the zip file
2. paste the content into the 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/f9461778-1723-441c-aae8-89ce185f963f)
`addons21\1908235722\user_files`
3. the the user_file folder should look like this:
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/3004e1a3-f9ea-4647-b821-2d45435f36d2)
4. Restart your anki and i think it should work :)

**Comment by omfgroflmfaol** [comment]
Thank you, it works!

**Comment by Dubuyu** [comment]
> https://we.tl/t-JtURvCggje

Hi, sorry, didn't manage to grab this file in time before it expired, is it the same as the one you resent or different?

**Comment by omfgroflmfaol** [comment]
Here you go @Dubuyu: https://we.tl/t-ZQkQEvzEUg

**Comment by Dubuyu** [comment]
> Here you go @Dubuyu: https://we.tl/t-ZQkQEvzEUg

Sorry, I meant the one that needs to be named init.py

**Comment by Unlucky-Life** [comment]
@Dubuyu try this init file: https://github.com/Unlucky-Life/ankimon/blob/2f3014b6cac17867285c751b268e72269a876fcf/src/Ankimon/__init__.py => and go into config and set ssh to false => this should solve your above issue

**Comment by Dubuyu** [comment]
Unfortunately still not working :(

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "urllib3.connectionpool", line 467, in _make_request
  File "urllib3.connectionpool", line 1096, in _validate_conn
  File "urllib3.connection", line 642, in connect
  File "urllib3.connection", line 782, in _ssl_wrap_socket_and_match_hostname
  File "urllib3.util.ssl_", line 470, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 514, in _ssl_wrap_socket_impl
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1041, in _create
  File "ssl", line 1310, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3.connectionpool", line 790, in urlopen
  File "urllib3.connectionpool", line 491, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests.adapters", line 486, in send
  File "urllib3.connectionpool", line 844, in urlopen
  File "urllib3.util.retry", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Unlucky-Life/ankimon/main/update_txt.md (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\IWong25\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 357, in <module>
    github_content, github_html_content = read_github_file(github_url)
  File "C:\Users\IWong25\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 317, in read_github_file
    response = requests.get(url)
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Unlucky-Life/ankimon/main/update_txt.md (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
