### ISSUE TITLE
Extension doesn't load

### ISSUE THREAD

**Issue by PKefka** [Unlucky-Life/ankimon#54]
Ankimon File checker says resource files icomplete and i should download the files.

Anki says: "Can't load some of the extensions: Ankimon"
I can search for updates which does nothing and the debug information is posted below.

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.6.25-1-MANJARO-x86_64-with-glibc2.39

When loading Ankimon:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/home/manjaro/.local/share/Anki2/addons21/1908235722/__init__.py", line 5834, in <module>
    license = License()
  File "/home/manjaro/.local/share/Anki2/addons21/1908235722/__init__.py", line 5789, in __init__
    self.initUI()
  File "/home/manjaro/.local/share/Anki2/addons21/1908235722/__init__.py", line 5797, in initUI
    html_content = self.read_html_file(f"{addon_dir}/license.html")  # Replace with the path to your HTML file
  File "/home/manjaro/.local/share/Anki2/addons21/1908235722/__init__.py", line 5829, in read_html_file
    with open(file_path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/manjaro/.local/share/Anki2/addons21/1908235722/license.html'

**Comment by CarlosJavierOrozco** [comment]
Hello. Same error for me. I use Kubuntu

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.5.0-27-generic-x86_64-with-glibc2.35

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/home/carlosjorozco/.local/share/Anki2/addons21/1908235722/__init__.py", line 5834, in <module>
    license = License()
  File "/home/carlosjorozco/.local/share/Anki2/addons21/1908235722/__init__.py", line 5789, in __init__
    self.initUI()
  File "/home/carlosjorozco/.local/share/Anki2/addons21/1908235722/__init__.py", line 5797, in initUI
    html_content = self.read_html_file(f"{addon_dir}/license.html")  # Replace with the path to your HTML file
  File "/home/carlosjorozco/.local/share/Anki2/addons21/1908235722/__init__.py", line 5829, in read_html_file
    with open(file_path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/carlosjorozco/.local/share/Anki2/addons21/1908235722/license.html'

**Comment by PKefka** [comment]
Got a pretty similar error on another machine with Fedora.

**Comment by Unlucky-Life** [comment]
@PKefka @CarlosJavierOrozco Hm I see, i think this is a pathing issue in linux.
Could you check if that path '/home/carlosjorozco/.local/share/Anki2/addons21/1908235722/license.html' => actually comes up with your anki folder ? or send me the path of your ankimon folder

**Comment by Unlucky-Life** [comment]
@PKefka @CarlosJavierOrozco 
This might be a quick fix but please download the following file: 
https://github.com/Unlucky-Life/ankimon/blob/57e32a4170596a50ef75f8d0152c9a5965e8fdcb/src/Ankimon/license.html
=> and drop this file into your ankimon folder.
Then restart Anki and check if this solved the issue

**Comment by PKefka** [comment]
> @PKefka @CarlosJavierOrozco This might be a quick fix but please download the following file: https://github.com/Unlucky-Life/ankimon/blob/57e32a4170596a50ef75f8d0152c9a5965e8fdcb/src/Ankimon/license.html => and drop this file into your ankimon folder. Then restart Anki and check if this solved the issue

That fixed it. The File is there but it's named LICENSE.html instead of license.html
