### ISSUE TITLE
Unable to "download resources"

### ISSUE THREAD

**Issue by strwberrys1234** [Unlucky-Life/ankimon#84]
Hi! This is the troubleshoot code, really not sure what to do. Tried deleting and redownloading again. 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-12.4-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/rebeccatsai/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 4165, in show_agreement_and_download_database
    pokeapi_db_downloader()
  File "/Users/rebeccatsai/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 4169, in pokeapi_db_downloader
    dlg = LoadingDialog(addon_dir)
  File "/Users/rebeccatsai/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 4117, in __init__
    self.start_download(addon_dir)
  File "/Users/rebeccatsai/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 4121, in start_download
    self.downloader = Downloader(addon_dir)
  File "/Users/rebeccatsai/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 3907, in __init__
    self.item_names = items_list
NameError: name 'items_list' is not defined

**Comment by strwberrys1234** [comment]
Please help me haha... I am going stir-crazy w/o my Ankimon.. redownloaded multiple times and restarted my computer. It's still giving me the same error message.

**Comment by Unlucky-Life** [comment]
@strwberrys1234 hey no worries i gotcha !

**Comment by Unlucky-Life** [comment]
@strwberrys1234 just update the addon and you it should fix the issue

**Comment by strwberrys1234** [comment]
it started downloading, thank you x10000000!!
